try catching unhandled exceptions since we're getting crashes during test
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1.ToArray()
   at RunProcessAsTask.ProcessEx.<>c__DisplayClass1_0.<RunAsync>b__2(Object sender, EventArgs args) in C:\projects\runprocessastask\src\RunProcessAsTask\ProcessEx.cs:line 50
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Diagnostics.Process.CompletionCallback(Object context, Boolean wasSignaled)
   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context(Object state, Boolean timedOut)